function fish_greeting
end
fish_add_path /home/jules/tools/lua-language-server/bin/nvim-linux64
fish_vi_key_bindings
alias nvim "/home/jules/nvim-linux64/bin/nvim"
alias v "/home/jules/nvim-linux64/bin/nvim"
set -x PATH /home/jules/tools/lua-language-server/bin/ $PATH
alias lbgmononoke "pkill -f mpv ; Bgblack ;  sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/mononoke.mp4" 
alias lbgramenShiba "pkill -f mpv ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/ramenShiba.mp4" 
alias lbgSleepingTeddyBear "pkill -f mpv ; Bgblack  ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/sleepingTeddyBear.mp4" 
alias lbgLonelyTree "pkill -f mpv  ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/LonelyTree.mp4" 
alias lbgLake "pkill -f mpv ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/LakeSakura.mp4" 
alias lbgRing "pkill -f mpv ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/bluering.mp4" 
alias lbgSakura "pkill -f mpv ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/sakura2.mp4" 
alias lbgSunset "pkill -f mpv ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/sunset.mp4" 
alias lbgSpace "pkill -f mpv  ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/space.mp4" 
alias lbgFireInSpace "pkill -f mpv ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/fireInSpace.mp4" 
alias lbgsword "pkill -f mpv ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/sword.mp4" 
alias lbgLuffy "pkill -f mpv ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/luffy.mp4" 
alias lbgbluekeys "pkill -f mpv ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/blueKeyLight.mp4"
alias lbgcatbeam "pkill -f mpv ; Bgblack ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/catBeam.mp4"
alias Bgcherryblossom "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/cherryblossom.jpg"
alias Bgblack "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/black.jpg"
alias Bganimegirl "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/animegirl.jpg"
alias Bgforestpath "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/forestpath.jpg"
alias Bgfantazypanorama "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/black.jpg"
alias BgjapPainting "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/japPainting.jpg"
alias Bgprettyface "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/prettyface.jpg"
alias Bgsakuradark "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/sakuradark.jpg"
alias BgsceneryPainted "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/sceneryPainted.jpg"
alias Bgweirdface "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/weirdfacebgred.jpg"
alias Bgxianxiahug "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/xianxiahug.jpg"
alias Bgcatmeme "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/catMeme.jpg"
alias Bgoldwolverine "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/oldWolverine.jpg"
alias Bgpanda "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/panda.jpg"
alias BgcatForest "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/catForest.jpg"
